# Generated by Django 5.1.4 on 2024-12-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuserfollower'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
